/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividadeluciano;

import atividadeluciano.*;
import javax.swing.JOptionPane;

/**
 *
 * @author silvio Collioni
 */
public class principal extends javax.swing.JFrame {

    private Cronometro cronometro;
    private int contagemResultado;
    Thread tm;

    public principal() {
        initComponents();
        cronometro = new Cronometro(tmili2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btStart2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tmili2 = new javax.swing.JTextField();
        painelValor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));
        getContentPane().setLayout(null);

        btStart2.setText("START");
        btStart2.setToolTipText("");
        btStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStart2ActionPerformed(evt);
            }
        });
        getContentPane().add(btStart2);
        btStart2.setBounds(210, 340, 100, 50);

        jButton5.setText("STOP");
        jButton5.setToolTipText("");
        jButton5.setActionCommand("START");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(320, 340, 100, 50);

        tmili2.setFont(new java.awt.Font("Tahoma", 0, 70)); // NOI18N
        tmili2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tmili2.setText("0");
        getContentPane().add(tmili2);
        tmili2.setBounds(40, 120, 490, 180);

        painelValor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ultimoResultado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        getContentPane().add(painelValor);
        painelValor.setBounds(40, 330, 160, 60);

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 340, 100, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ESCOLHA UM NÚMERO E TENTE ACERTAR NOVAMENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 470, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStart2ActionPerformed
        // TODO add your handling code here:
        cronometro.start();

    }//GEN-LAST:event_btStart2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cronometro.stop();
        if(painelValor.getText().equals("")){
            
        this.contagemResultado =  cronometro.getContagem();
        painelValor.setText(Integer.toString (this.contagemResultado));
        } 
        else 
        {
         if ( contagemResultado == cronometro.getContagem()){
             JOptionPane.showMessageDialog(this, "VOCÊ VENCEU");
            
         } else{
             JOptionPane.showMessageDialog(this, "VOCÊ PERDEU");
         }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        cronometro.stop();
        painelValor.setText("");
        tmili2.setText("0");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStart2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel painelValor;
    private javax.swing.JTextField tmili2;
    // End of variables declaration//GEN-END:variables
}
